name: Build Pages Deployment

on:
    - workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Flutter Setup
              uses: subosito/flutter-action@v2
              with: 
                channel: stable
                flutter-version: 3.35.5
            - name: Build
              run: flutter build web --csp --no-web-resources-cdn --wasm --base-href=/class_demo/
            - name: Upload
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/web/
            - name: Deploy
              uses: actions/deploy-pages@v4
              